version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "6500:6500"
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
